name = "AtmosphericDeposition"
uuid = "1a52f20c-0d16-41d8-a00a-b2996d86a462"
version = "0.3.0"
authors = ["EarthSciML authors and contributors"]

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
EarthSciMLBase = "e53f1632-a13c-4728-9402-0c66d48804b0"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Aerosol = "8510b696-cc45-4a64-84d0-47f429ca1505"
EarthSciData = "a293c155-435f-439d-9c11-a083b6b47337"
GasChem = "58070593-4751-4c87-a5d1-63807d11d76c"

[extensions]
AerosolExt = "Aerosol"
EarthSciDataExt = "EarthSciData"
GasChemExt = "GasChem"

[compat]
Aerosol = "0.4"
DataInterpolations = "6, 7, 8"
DynamicQuantities = "1"
EarthSciData = "0.15"
EarthSciMLBase = "0.25"
GasChem = "0.12"
ModelingToolkit = "11"
OrdinaryDiffEqDefault = "1"
OrdinaryDiffEqRosenbrock = "1.10.1"
StaticArrays = "1"
Symbolics = "7"
TestItemRunner = "1.1.0"
julia = "1"

[extras]
Aerosol = "8510b696-cc45-4a64-84d0-47f429ca1505"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EarthSciData = "a293c155-435f-439d-9c11-a083b6b47337"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "Dates", "EarthSciData", "Aerosol", "OrdinaryDiffEqDefault", "OrdinaryDiffEqRosenbrock", "Symbolics", "TestItemRunner"]
