[deps]
AtmosphericDeposition = "1a52f20c-0d16-41d8-a00a-b2996d86a462"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
EarthSciMLBase = "e53f1632-a13c-4728-9402-0c66d48804b0"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Catalyst = "16"
DataFrames = "1"
DifferentialEquations = "7"
Documenter = "1"
DynamicQuantities = "1"
EarthSciMLBase = "0.24"
ModelingToolkit = "10"
OrdinaryDiffEqDefault = "1"
Plots = "1"
Symbolics = "6"
